return
{
	"EdenEast/nightfox.nvim",
	config = function()
		require("nightfox").setup({
			options = {
				transparent = false
			}
		})
		vim.cmd("colorscheme terafox")
	end
}
-- {
-- 	"vague2k/vague.nvim",
-- 	config = function()
-- 		require("vague").setup({
-- 			-- optional configuration here
-- 			transparent = true,
-- 			style = {
-- 				-- "none" is the same thing as default. But "italic" and "bold" are also valid options
-- 				boolean = "none",
-- 				number = "none",
-- 				float = "none",
-- 				error = "none",
-- 				comments = "none",
-- 				conditionals = "none",
-- 				functions = "none",
-- 				headings = "bold",
-- 				operators = "none",
-- 				strings = "none",
-- 				variables = "none",
--
-- 				-- keywords
-- 				keywords = "none",
-- 				keyword_return = "none",
-- 				keywords_loop = "none",
-- 				keywords_label = "none",
-- 				keywords_exception = "none",
--
-- 				-- builtin
-- 				builtin_constants = "none",
-- 				builtin_functions = "none",
-- 				builtin_types = "none",
-- 				builtin_variables = "none",
-- 			},
-- 			colors = {
-- 				func = "#bc96b0",
-- 				keyword = "#787bab",
-- 				-- string = "#d4bd98",
-- 				string = "#8a739a",
-- 				-- string = "#f2e6ff",
-- 				-- number = "#f2e6ff",
-- 				-- string = "#d8d5b1",
-- 				number = "#8f729e",
-- 				-- type = "#dcaed7",
-- 			},
-- 		})
-- 		vim.cmd("colorscheme vague")
-- 	end,
-- }
-- {
-- 	'sainnhe/gruvbox-material',
-- 	lazy = false,
-- 	priority = 1000,
-- 	config = function()
-- 			transparent =true
-- 		-- Optionally configure and load the colorscheme
-- 		-- directly inside the plugin declaration.
-- 		-- vim.g.gruvbox_material_enable_italic = true
-- 		vim.g.gruvbox_material_transparent_background = 1
-- 		vim.cmd.colorscheme('gruvbox-material')
-- 	end
-- }
-- {
-- 	'Mofiqul/dracula.nvim',
-- 	lazy = false,
-- 	priority = 1000,
-- 	config = function()
--  		require("dracula").setup({
-- 			transparent_bg = true,
--  		})
-- 		vim.cmd.colorscheme('dracula')
-- 	end
-- }
-- {
-- 	"catppuccin/nvim",
-- 	name = "catppuccin",
-- 	priority = 1000,
-- 	config = function()
-- 		require("catppuccin").setup({
-- 			flavour = "auto", -- latte, frappe, macchiato, mocha
-- 			background = { -- :h background
-- 				light = "latte",
-- 				dark = "mocha",
-- 			},
-- 			transparent_background = true, -- disables setting the background color.
-- 			show_end_of_buffer = false, -- shows the '~' characters after the end of buffers
-- 			term_colors = false,  -- sets terminal colors (e.g. `g:terminal_color_0`)
-- 			dim_inactive = {
-- 				enabled = false,  -- dims the background color of inactive window
-- 				shade = "dark",
-- 				percentage = 0.15, -- percentage of the shade to apply to the inactive window
-- 			},
-- 			no_italic = false,    -- Force no italic
-- 			no_bold = false,      -- Force no bold
-- 			no_underline = false, -- Force no underline
-- 			styles = {            -- Handles the styles of general hi groups (see `:h highlight-args`):
-- 				comments = { "italic" }, -- Change the style of comments
-- 				conditionals = { "italic" },
-- 				loops = {},
-- 				functions = {},
-- 				keywords = {},
-- 				strings = {},
-- 				variables = {},
-- 				numbers = {},
-- 				booleans = {},
-- 				properties = {},
-- 				types = {},
-- 				operators = {},
-- 				-- miscs = {}, -- Uncomment to turn off hard-coded styles
-- 			},
-- 			color_overrides = {},
-- 			custom_highlights = {},
-- 			default_integrations = true,
-- 			integrations = {
-- 				cmp = true,
-- 				gitsigns = true,
-- 				nvimtree = true,
-- 				treesitter = true,
-- 				notify = false,
-- 				mini = {
-- 					enabled = true,
-- 					indentscope_color = "",
-- 				},
-- 				-- For more plugins integrations please scroll down (https://github.com/catppuccin/nvim#integrations)
-- 			},
-- 		})
--
-- 		-- catppuccin catppuccin-latte, catppuccin-frappe, catppuccin-macchiato, catppuccin-mocha
-- 		vim.cmd.colorscheme "catppuccin"
-- 	end
-- }
